CREATE DATABASE MELOOS;
USE MELOOS;
START TRANSACTION;
CREATE TABLE ADMINS (
	ID_ADMIN INT PRIMARY KEY auto_increment,
    NOME_ADMIN VARCHAR(255),
    LOGIN_ADMIN VARCHAR(255),
    SENHA_ADMIN VARCHAR(255)
);
CREATE TABLE COLABORADORES (
	ID_COLABORADOR INT PRIMARY KEY auto_increment,
    NOME_COLABORADOR VARCHAR(255),
    IDENTIFICACAO_COLABORADOR VARCHAR(255),
    LOGIN_COLABORADOR VARCHAR(255),
    SENHA_COLABORADOR VARCHAR(255)
);
CREATE TABLE SETORES (
	ID_SETOR INT PRIMARY KEY auto_increment,
    NOME_SETOR VARCHAR(255),
    IDENTIFICACAO_SETOR VARCHAR(255)
);
CREATE TABLE EQUIPAMENTOS (
	ID_EQUIPAMENTO INT PRIMARY KEY auto_increment,
    NOME_EQUIPAMENTO VARCHAR(255),
    IDENTIFICACAO_EQUIPAMENTO VARCHAR(255)
);
CREATE TABLE TAREFAS (
	ID_TAREFA INT PRIMARY KEY auto_increment,
    OCORRENCIA_TAREFA VARCHAR(255),
    DESCRICAO_TAREFA VARCHAR(255),
    DATA_TAREFA VARCHAR(255),
    TERMINO_TAREFA VARCHAR(255),
    CLASSIFICACAO_TAREFA VARCHAR(255),
    MINUTOS_TAREFA INT,
    ID_SETOR INT,
    ID_EQUIPAMENTO INT,
    ID_COLABORADOR INT
);
ALTER TABLE TAREFAS ADD CONSTRAINT FK_SETOR FOREIGN KEY (ID_SETOR) REFERENCES SETORES (ID_SETOR) ON DELETE SET NULL;
ALTER TABLE TAREFAS ADD CONSTRAINT FK_EQUIPAMENTO FOREIGN KEY (ID_EQUIPAMENTO) REFERENCES EQUIPAMENTOS (ID_EQUIPAMENTO) ON DELETE SET NULL;
ALTER TABLE TAREFAS ADD CONSTRAINT FK_COLABORADOR FOREIGN KEY (ID_COLABORADOR) REFERENCES COLABORADORES (ID_COLABORADOR) ON DELETE SET NULL;